baseURL = 'https://dineshghimire01.github.io/web/'
languageCode = 'en-us'
theme = 'ananke'

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Education"
    url = "/education/"
    weight = 2

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3

[[menu.main]]
    name = "Awards"
    url = "/awards/"
    weight = 4

  [[menu.main]]
    name = "CV"
    url = "/files/CV_Dinesh.pdf"
    weight = 5

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6


publishDir = "public"
relativeURLs = false
canonifyURLs = true
